name: elbkind_test_01
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21028
title: 'Unsere Elbkind Test Site '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eff2f4'
    - '#009fe3'
    - '#c3c9c7'
    - '#6c7c79'
    - '#343434'
  brandStrength: 0
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
